version: "3.7"

networks:
  traefik:
    name: traefik
    external: true

services:
  web:
    build: .
    image: nonfiction/bedrock:web
    env_file: .env
    environment:
      WP_ENV: development
    volumes:
      - type: bind
        source: .
        target: /srv
        read_only: true
      - type: bind
        source: ./config/vhost.conf
        target: /etc/apache2/sites-available/000-default.conf
        read_only: true
    expose:
      - 80
      - 443
    networks:
      - traefik

  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: nonfiction/bedrock:dev

  tasks:
    build:
      context: .
      dockerfile: Dockerfile-tasks
    image: nonfiction/bedrock:tasks
    
  wp:
    build:
      context: .
      dockerfile: Dockerfile-tasks
    image: nonfiction/bedrock:wp
    entrypoint: wp
    command: ""