# docker-compose.yml (base)
version: "3.7"
services:
  
  # Bedrock WordPress on Apache
  srv:
    build: .
    image: nonfiction/${APP_NAME}:latest
    env_file: .env
    environment:
      - APP_HOST
    volumes:
      - type: volume
        source: uploads
        target: /srv/web/app/uploads
    expose: 
      - 443

  # WP-CLI
  wp:
    image: nonfiction/${APP_NAME}:latest
    env_file: .env
    environment:
      - APP_HOST
    entrypoint: /usr/local/bin/wp
    working_dir: /srv 
    command: 'core version'
    volumes:
      - type: volume
        source: uploads
        target: /srv/web/app/uploads

  # Webpack Dev Server
  dev:
    image: nonfiction/bedrock:dev
    working_dir: /srv/web/app/site
    command: webpack-dev-server --hide-modules --hot
    volumes:
      - type: bind
        source: ./site
        target: /srv/web/app/site
      - type: volume
        source: node_modules
        target: /srv/web/app/site/node_modules
    expose:
      - 443

  # Manage files and databases
  env:
    image: nonfiction/bedrock:env
    env_file: .env
    volumes:
      - type: volume
        source: uploads
        target: /uploads
      - type: bind
        source: /tmp/${APP_NAME}/uploads
        target: /host

# traefik reverse-proxy defined by docker-host 
networks:
  traefik:
    name: traefik
    external: true

# speed up build times by storing packages, persist uploads
volumes:
  uploads:
  node_modules:
