# MySQL client to create users & databases
FROM mysql:latest

RUN set -ex; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
    curl \
    less \
    zip \
    unzip \
    php \
    php-zip \
    ruby \
  ;

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  
# WP-CLI
RUN set -ex; \
  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; \
  chmod +x wp-cli.phar; \
  mv wp-cli.phar /usr/local/bin/wp-cli.phar; \
  echo '#!/bin/sh' >> /usr/local/bin/wp; \
  echo 'wp-cli.phar "$@" --allow-root' >> /usr/local/bin/wp; \
  chmod +x /usr/local/bin/wp;

# Thor
RUN gem install thor dotenv
COPY ./Thorfile /bin/tasks
RUN chmod +x /bin/tasks

WORKDIR /srv/

RUN touch /.env

ENTRYPOINT ["tasks"]

CMD ["list"]
