version: "3.7"

networks:
  traefik:
    name: traefik
    external: true

services:
  web:
    build: .
    image: nonfiction/bedrock:latest
    env_file: .env
    environment:
      WP_ENV: development
    volumes:
      - type: bind
        source: .
        target: /srv
        read_only: true
      - type: bind
        source: ./config/vhost.conf
        target: /etc/apache2/sites-available/000-default.conf
        read_only: true
    expose:
      - 80
      - 443
    networks:
      - traefik
